apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: development-randomquotes
resources:
  - ../../base
images:
  - name: bobjwalker99/randomquotes-k8s
    newName: dukeofchutney/images
    newTag: "0.1.102"
patches:
  - target:
      kind: Ingress
      name: randomquotes-ingress-nginx
    path: randomquotes-ingress-nginx.yaml
